name: Digest-TransformPath
version: 0.02
abstract: Create digests describing multi-step data transformation paths
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Digest::MD5: 2.00
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
